PLATFORM_WIDTH = 32
PLATFORM_HEIGHT = 32

map1 = [
       "csssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssz",
       "d                                                                         a",
       "d                                                                         a",
       "d                               www                                       a",
       "d            ww     wwwwwwwwww         ww  ww ww  wwww                    a",
       "d                                   wwww                                  a",
       "dw                ww      w                                               a",
       "d                             w                                           a",
       "d                   www                                                   a",
       "d                                                                         a",
       "d              w                                                          a",
       "d      www                                           wwwwwwwwwwwww        a",
       "d                                                                         a",
       "d   wwwwwwwwwww                                                           a",
       "d                                                                         a",
       "d                w                        wwwwwwwwwww                     a",
       "d                   ww                                                    a",
       "d                          w                                              a",
       "d                     w                              w                    a",
       "d                             w                           wwwwwwwww       a",
       "d                                                    w                    a",
       "d                               w                                         a",
       "d                                                    w                    a",
       "d                           w                 wwwwwwwww                   a",
       "d                                                                         a",
       "d                                ww                       wwwwwwwww       a",
       "d                                                                         a",
       "d                                               wwwwwwwwww                a",
       "d                                     www                                 a",
       "d                                                                         a",
       "d                                                                         a",
       "ewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwq"]